<?php

declare(strict_types=1);

$menuApiBase = getenv('SP_MENU_API_BASE') ?: 'https://script.google.com/macros/s/YOUR_DEPLOYMENT_ID/exec';
$menuApiToken = getenv('SP_MENU_API_TOKEN') ?: '';
$menuSheetId = getenv('SP_MENU_SHEET_ID') ?: '';
$whatsAppNumber = getenv('SP_WHATSAPP_NUMBER') ?: '5210000000000';

return [
    'meta' => [
        'title' => 'Bloom Latte - Pedidos Dinámicos',
        'description' => 'Base PHP reutilizable para menús dinámicos con carrito, personalización y envío por WhatsApp.',
    ],
    'brand' => [
        'name' => 'Bloom Latte 🌟',
        'subtitle' => 'Personaliza tu pedido',
    ],
    'ui' => [
        'loadingText' => 'Cargando menú delicioso...',
        'loadingErrorTitle' => '¡Ups! Problemas de conexión',
        'loadingErrorMessage' => 'No pudimos cargar el menú, verifica tu internet.',
        'retryLabel' => 'Reintentar',
        'emptyMenuLabel' => 'No hay productos disponibles por el momento.',
        'modalPlaceholderName' => 'Producto',
        'modalPlaceholderDescription' => 'Descripción',
        'sizeLabel' => 'Selecciona Tamaño',
        'quantityLabel' => 'Cantidad',
        'subtotalLabel' => 'Subtotal',
        'addToCartLabel' => 'Agregar al pedido',
        'cartTitle' => 'Tu Carrito',
        'paymentLabel' => 'Método de Pago',
        'customerNameLabel' => 'Tu Nombre',
        'customerNamePlaceholder' => 'Ej. Juan Pérez',
        'customerNameRequiredPlaceholder' => '¡Necesitamos tu nombre!',
        'totalLabel' => 'Total',
        'sendOrderLabel' => 'Enviar Pedido',
        'observationsLabel' => 'Observaciones',
        'observationsPlaceholder' => 'Ej. Sin popote, endulzante aparte, etc. (Opcional)',
        'emptyCartLabel' => 'Tu carrito está vacío',
        'noExtrasLabel' => 'Sin extras',
        'noteLabel' => 'Nota',
        'soldOutLabel' => 'Agotado',
        'fromLabel' => 'Desde',
        'whyDisabledMessage' => 'Configura WhatsApp antes de enviar pedidos.',
    ],
    'payments' => [
        'Efectivo' => 'Efectivo',
        'Transferencia' => 'Transf.',
        'Tarjeta' => 'Tarjeta',
    ],
    'integrations' => [
        'menuApiBase' => $menuApiBase,
        'menuApiToken' => $menuApiToken,
        'menuSheetId' => $menuSheetId,
        'whatsappNumber' => $whatsAppNumber,
    ],
    'demoData' => [
        'modificadores' => [
            [
                'ID Modificador' => 'milk',
                'Nombre a mostrar en UI' => 'Tipo de leche',
                'Reglas' => 'Obligatorio',
            ],
            [
                'ID Modificador' => 'extras',
                'Nombre a mostrar en UI' => 'Extras',
                'Reglas' => 'Opcional, múltiple',
            ],
        ],
        'seleccionables' => [
            [
                'ID Opción' => 'whole-milk',
                'ID Modificador (Relación)' => 'milk',
                'Etiqueta (UI)' => 'Leche entera',
                'Precio Extra' => 0,
                'Disponible' => true,
            ],
            [
                'ID Opción' => 'oat-milk',
                'ID Modificador (Relación)' => 'milk',
                'Etiqueta (UI)' => 'Leche de avena',
                'Precio Extra' => 12,
                'Disponible' => true,
            ],
            [
                'ID Opción' => 'almond-milk',
                'ID Modificador (Relación)' => 'milk',
                'Etiqueta (UI)' => 'Leche de almendra',
                'Precio Extra' => 15,
                'Disponible' => true,
            ],
            [
                'ID Opción' => 'extra-shot',
                'ID Modificador (Relación)' => 'extras',
                'Etiqueta (UI)' => 'Shot extra',
                'Precio Extra' => 18,
                'Disponible' => true,
            ],
            [
                'ID Opción' => 'lavender-foam',
                'ID Modificador (Relación)' => 'extras',
                'Etiqueta (UI)' => 'Espuma de lavanda',
                'Precio Extra' => 14,
                'Disponible' => true,
            ],
            [
                'ID Opción' => 'cold-foam',
                'ID Modificador (Relación)' => 'extras',
                'Etiqueta (UI)' => 'Cold foam',
                'Precio Extra' => 16,
                'Disponible' => true,
            ],
        ],
        'productos' => [
            [
                'Nombre' => 'Bloom Latte',
                'Descripción' => 'Espresso con notas florales y leche vaporizada.',
                'Categoria' => 'Bebidas',
                'C' => 72,
                'M' => 84,
                'G' => 96,
                'XL' => '',
                'Disponible-Global' => true,
                'Disponible-C' => true,
                'Disponible-M' => true,
                'Disponible-G' => true,
                'Disponible-XL' => false,
                'Modificadores Aplicables' => 'milk, extras',
            ],
            [
                'Nombre' => 'Rose Matcha',
                'Descripción' => 'Matcha ceremonial con crema ligera de rosa.',
                'Categoria' => 'Bebidas',
                'C' => 79,
                'M' => 91,
                'G' => 103,
                'XL' => '',
                'Disponible-Global' => true,
                'Disponible-C' => true,
                'Disponible-M' => true,
                'Disponible-G' => true,
                'Disponible-XL' => false,
                'Modificadores Aplicables' => 'milk, extras',
            ],
            [
                'Nombre' => 'Bloom Toast',
                'Descripción' => 'Pan artesanal con ricotta batida, miel y fruta.',
                'Categoria' => 'Comida',
                'C' => 118,
                'M' => '',
                'G' => '',
                'XL' => '',
                'Disponible-Global' => true,
                'Disponible-C' => true,
                'Disponible-M' => false,
                'Disponible-G' => false,
                'Disponible-XL' => false,
                'Modificadores Aplicables' => 'extras',
            ],
            [
                'Nombre' => 'Panqué de lavanda',
                'Descripción' => 'Rebanada del día con glaseado cítrico.',
                'Categoria' => 'Postres',
                'C' => 64,
                'M' => '',
                'G' => '',
                'XL' => '',
                'Disponible-Global' => true,
                'Disponible-C' => true,
                'Disponible-M' => false,
                'Disponible-G' => false,
                'Disponible-XL' => false,
                'Modificadores Aplicables' => '',
            ],
        ],
    ],
];
